config/routes.rb
Rails.application.routes.draw do
  begin
    cloudfuji_routes

    if Cloudfuji::Platform.on_cloudfuji?
      # Remove existing authentication routes
      r = Rails.application.routes
      r.set.routes.reject! {|r| %w(login logout).include? r.name }
      r.set.send "clear_cache!"
      # Setup cloudfuji authentication routes
      cloudfuji_authentication_routes
    end
  rescue => e
    puts "Error loading the Cloudfuji routes:"
    puts "#{e.inspect}"
  end

  namespace :admin do
    resources :event_rules, :only => :index do
      post :update, :on => :collection
    end
  end

  resources :unknown_emails, :only => :index do
    member do
      delete :ignore
      put    :convert
    end
  end
end

app/models/event_rule.rb
class EventRule < ActiveRecord::Base

  # event category validations
  validates_presence_of :event_category
  validates_presence_of :lead_attribute,     :if => lambda { self.event_category  == 'lead_attribute_changed' }
  validates_presence_of :cloudfuji_event,    :if => lambda { self.event_category  == 'cloudfuji_event_received' }
  validates_presence_of :page_name, :app_id, :if => lambda { self.cloudfuji_event == 'page_loaded' }

  # action validations
  validates_presence_of :action
  validates_presence_of :tag, :if => lambda { %w(add_tag remove_tag).include?(self.action) }
  validates_presence_of :mailing_list, :mailing_list_group, :mailing_list_grouping, :if => lambda { self.action == "add_to_mailing_list_group" }

  validates_numericality_of :change_score_by, :only_integer => true, :if => lambda { self.action == 'change_lead_score' }

  validates_numericality_of :limit_per_lead,  :only_integer => true, :allow_blank => true

  has_many :lead_event_rule_counts

  def process(lead, params = {})
    # How many times this rule has been applied to a given Lead
    count = LeadEventRuleCount.find_by_lead_id_and_event_rule_id(lead, self) ||
            LeadEventRuleCount.new(:lead => lead, :event_rule => self)
    # Don't apply this rule more than limit_per_lead, if set
    unless limit_per_lead.present? && count.count > limit_per_lead
      # If :match is present, only apply the rule if data matches string
      if match.blank? || event_matches?(params)
        if (app_id.blank? && page_name.blank?) || page_and_app_matches?(params)
          # Run the action method if defined
          if respond_to?(action)
            send(action, lead, params)
            # Increment and save count of rule/lead applications
            count.count += 1
            count.save
          else
            raise "Do not know how to process '#{action}' action."
          end
        end
      end
    end
  end

  # Actions
  # -----------------------------------------------------------------
  def change_lead_score(lead, match_data)
    lead.without_versioning do
      lead.update_attribute :score, lead.score + change_score_by
    end
    # Add history event to lead, to record change of score
    lead.versions.create! :event => "Rule for #{human_event_label}: Score changed by #{change_score_by} points. (New total: #{lead.score})"
  end

  def send_notification(lead, match_data)
    if ::Cloudfuji::Platform.on_cloudfuji?
      # Fire a Cloudfuji event
      message = case event_category
      when 'cloudfuji_event_received'
        "Cloudfuji event was received - '#{cloudfuji_event}'"
      when 'lead_attribute_changed'
        "Lead \"#{lead.full_name}\" was updated - #{lead_attribute} was changed from '#{match_data['old_value']}' to '#{match_data['new_value']}'."
      end

      User.all.each do |user|
        user.notify(lead.full_name, message, "crm") if !user.ido_id.nil?
      end

    end
  end

  def add_tag(lead, match_data)
    lead.tag_list << tag
    save_lead_without_versioning_or_observers(lead)
    lead.versions.create! :event => "Rule for #{human_event_label}: Added tag '#{tag}'"
  end

  def remove_tag(lead, match_data)
    lead.tag_list -= [tag]
    save_lead_without_versioning_or_observers(lead)
    lead.versions.create! :event => "Rule for #{human_event_label}: Removed tag '#{tag}'"
  end

  def add_to_mailing_list_group(lead, match_data)
    # Send a Cloudfuji event which results in a call to the Mailchimp API,
    # and adds InterestGroup to lead.
    event = {
      :category => :mailing_list_group,
      :name     => :added,
      :data     => {
        :email                 => lead.email,
        :customer_ido_id       => lead.ido_id,
        :user_ido_id           => user_ido_id,
        :mailing_list          => mailing_list,
        :mailing_list_grouping => mailing_list_grouping,
        :mailing_list_group    => mailing_list_group
      }
    }

    puts "Publishing Cloudfuji Event: #{event.inspect}"
    ::Cloudfuji::Event.publish(event)
  end

  private

  def event_matches?(params)
    test_string = case_insensitive_matching ? match.downcase : match
    case event_category
    when 'cloudfuji_event_received'
      match_string = params['data'].inspect
      match_string.downcase! if case_insensitive_matching
      match_string.include?(test_string)
    when 'lead_attribute_changed'
      match_string = params['new_value'].to_s.dup
      match_string.downcase! if case_insensitive_matching
      match_string == test_string.to_s
    end
  end

  def page_and_app_matches?(params)
    (page_name.blank? || page_name == params["data"]["page"]) &&
    (app_id.blank? || app_id == params["app_id"])
  end

  def human_event_label
    case event_category
    when 'cloudfuji_event_received'; "Cloudfuji event - '#{cloudfuji_event}'"
    when 'lead_attribute_changed';   "Lead update - '#{lead_attribute}'"
    end
  end

  def save_lead_without_versioning_or_observers(lead)
    Lead.observers.disable :cloudfuji_lead_observer do
      lead.without_versioning do
        lead.save
      end
    end
  end
end

app/controllers/admin/event_rules_controller.rb
class Admin::EventRulesController < Admin::ApplicationController
  before_filter :require_user
  before_filter "set_current_tab('admin/event_rules')", :only => [ :index, :update ]

  # GET /admin/event_rules
  #----------------------------------------------------------------------------
  def index
    @event_rules = EventRule.all
    @event_rules << EventRule.new if @event_rules.empty?

    respond_to do |format|
      format.html # index.html.haml
    end
  end

  # PUT /admin/event_rules
  #----------------------------------------------------------------------------
  def update
    # Create rules without ids,
    # destroy rules with '_destroy' param,
    # update rules with ids
    @event_rules = []
    params[:event_rules].each do |index, data|
      if data["id"].blank?
        @event_rules << EventRule.create(data)
      else
        if rule = EventRule.find_by_id(data["id"])
          if data["_destroy"]
            rule.destroy
          else
            rule.update_attributes data
            @event_rules << rule
          end
        end
      end
    end

    if @event_rules.all?(&:valid?)
      flash[:notice] = "All rules were saved successfully."
    else
      flash[:error] = render_to_string(:partial => "errors").html_safe
    end

    respond_to do |format|
      format.html { render "index" }
    end
  end

end

app/helpers/admin/event_rules_helper.rb
module Admin::EventRulesHelper

  def add_event_rule_button(f)
    fields = f.fields_for "new_event_rule", EventRule.new do |builder|
      render("form", :r => builder, :index => "new_event_rule")
    end
    button_tag 'Add New Rule', :class => "add_event_rule", "data-content" => "#{fields}"
  end

  def event_category_select(form)
    form.select :event_category, [
      ["Cloudfuji event", :cloudfuji_event_received],
      ["Page loaded",     :page_loaded],
      ["Lead attribute",  :lead_attribute_changed]
    ], {}, :class => "event_category_select"
  end

  def action_select(form)
    form.select :action, [
      ["change Lead score",    :change_lead_score],
      ["send notification",    :send_notification],
      ["add tag",              :add_tag],
      ["remove tag",           :remove_tag],
      ["add to mailing group", :add_to_mailing_list_group]
    ], {}, :class => "action_select"
  end

  # Generates divs with form field groups for event rules
  def fields_for_event_rule_group(object, subjects, field)
    subjects = [subjects].flatten
    content_tag(:div, :class => subjects.map {|s| "#{field}_#{s}" }.join(" ") << " #{field}_fields",
                      :style => (subjects.none? {|s| s == object.send(field) } ? "display: none;" : "")) do
      yield
    end
  end

  def event_fields_for(object, events, &content)
    fields_for_event_rule_group(object, events, 'event_category', &content)
  end

  def action_fields_for(object, actions, &content)
    fields_for_event_rule_group(object, actions, 'action', &content)
  end

  def lead_attributes
    Lead.attribute_names - %w(id deleted_at updated_at created_at)
  end

end

app/views/admin/event_rules/_errors.html.haml
- invalid_rules = @event_rules.select{|r| r.errors.any? }
- if invalid_rules.any?
  There were (#{invalid_rules.size}) invalid rules:
  %br
  - invalid_rules.each_with_index do |rule, i|
    %strong= (i + 1).to_s << "."
    = rule.errors.full_messages.join(", ")
    %br

app/views/admin/event_rules/_form.html.haml
%li.event_rule{"data-index" => index}
  = link_to image_tag('delete.png', :size => '16x16', :alt => 'Remove Rule'), nil, :class => "remove_event_rule"

  = r.hidden_field(:id) unless r.object.new_record?

  If
  = event_category_select(r)

  = event_fields_for(r.object, 'cloudfuji_event_received') do
    = r.text_field :cloudfuji_event, :class => "cloudfuji_event_input"
    is received, and contains

  = event_fields_for(r.object, 'page_loaded') do
    = r.text_field :page_name, :class => "page_name_input"
    on app ID
    = r.text_field :app_id, :class => "app_id_input"

  = event_fields_for(r.object, 'lead_attribute_changed') do
    = r.select :lead_attribute, lead_attributes, :class => "lead_attribute", :include_blank => true
    changes, and equals

  = event_fields_for(r.object, %w(cloudfuji_event_received lead_attribute_changed)) do
    = content_tag(:small, "(optional)") << ":".html_safe
    = r.text_field :match, :class => "match_input"
    %small
      (Case insensitive?
      = r.check_box(:case_insensitive_matching) << h(")")

  then
  = action_select(r)

  = action_fields_for(r.object, 'change_lead_score') do
    by
    = r.text_field :change_score_by, :class => "numeric_input"
    points.

  -# Add/Remove tag actions share the same field
  = action_fields_for(r.object, %w(add_tag remove_tag)) do
    = r.text_field :tag, :class => "tag_input"

  = action_fields_for(r.object, %w(add_to_mailing_list_group)) do
    = r.text_field :mailing_list_group, :class => "mailing_list_group_input"
    in grouping
    = r.text_field :mailing_list_grouping, :class => "mailing_list_grouping_input"
    on list
    = r.text_field :mailing_list, :class => "mailing_list_input"
    %br
    -# TEMPORARY WORKAROUND
    %small{:style => "margin-left:26px;display:inline-block;padding-top:14px;"} Umi user Ido ID:
    = r.text_field :user_ido_id

  = action_fields_for(r.object, %w(change_lead_score send_notification)) do
    %small
      (Limit per lead:
      = r.text_field(:limit_per_lead, :class => "numeric_input") << h(")")

app/views/admin/event_rules/index.html.haml
:javascript
  var observed_cloudfuji_events = #{Cloudfuji::Data.observed_events.map(&:to_s).inspect};

.title
  Event Rules

.list
  = form_for :event_rules do |f|
    %ul#event_rules
      - @event_rules.each_with_index do |rule, i|
        = f.fields_for i.to_s, rule do |r|
          = render "form", :r => r, :index => i

    .buttonbar.event_rules_buttons
      = add_event_rule_button(f)
      .save_or_cancel
        = submit_tag 'Save', :name => :save
        #{t :or}
        = link_to "Cancel", admin_event_rules_path