config/routes.rb
Rails.application.routes.draw do
  begin
    cloudfuji_routes

    if Cloudfuji::Platform.on_cloudfuji?
      # Remove existing authentication routes
      r = Rails.application.routes
      r.set.routes.reject! {|r| %w(login logout).include? r.name }
      r.set.send "clear_cache!"
      # Setup cloudfuji authentication routes
      cloudfuji_authentication_routes
    end
  rescue => e
    puts "Error loading the Cloudfuji routes:"
    puts "#{e.inspect}"
  end

  namespace :admin do
    resources :event_rules, :only => :index do
      post :update, :on => :collection
    end
  end

  resources :unknown_emails, :only => :index do
    member do
      delete :ignore
      put    :convert
    end
  end
end

app/controllers/unknown_emails_controller.rb
class UnknownEmailsController < ApplicationController
  before_filter :set_current_tab

  def index
    # Fetch all emails that don't belong to an
    # entity, and aren't in the 'ignored_emails' table.
    sql = %Q{SELECT * from emails 
      WHERE mediator_id IS NULL 
      AND NOT EXISTS (
        SELECT DISTINCT(email) FROM ignored_emails 
        WHERE email = emails.sent_from 
        OR email = emails.sent_to)} 
    @unknown_emails = Email.paginate_by_sql(sql, :page => params[:page])
    
    respond_with @unknown_emails
  end

  # Delete email and ignore all emails from this address
  def ignore
    @email = Email.find(params[:id])
    unless address = params[:email]
      if @email.direction == 'received'
        address = @email.sent_from
      elsif @email.direction == 'sent'
        address = @email.sent_to
      end
    end

    if address.present? 
      IgnoredEmail.create :email => address
      @email.destroy
      flash[:notice] = "All emails from #{address} will be ignored."
    else
      flash[:error] = "Could not determine whether this email was sent or received!"
    end
    redirect_to unknown_emails_path
  end

  # Create lead and attach this email to new lead
  def convert
    address = params[:email]

    if address.present?
      # Attach all orphaned emails that are from / to address
      @emails = Email.all(:conditions => [%Q{
        mediator_id IS NULL
        AND (emails.sent_from LIKE ?
          OR emails.sent_to LIKE ?)
      }, "%#{address}%", "%#{address}%"])

      lead = Lead.create :email      => address,
                         :first_name => address.split("@").first,
                         :last_name  => address.split("@").last,
                         :user       => current_user,
                         :emails     => @emails

      link_to_lead = ActionController::Base.helpers.link_to(lead_url(lead), lead_url(lead))
      flash[:notice] = "Created lead and attached email(s): #{link_to_lead}".html_safe
    else
      flash[:error] = "Must provide :email param!"
    end
    redirect_to unknown_emails_path

  end
end

app/helpers/unknown_emails_helper.rb
module UnknownEmailsHelper
end

app/views/unknown_emails/_unknown_email.html.haml
%tr.highlight[unknown_email]
  - addresses = (unknown_email.direction == 'received' ? unknown_email.sent_from : unknown_email.sent_to).split(";")
  %td= unknown_email.direction.to_s.capitalize
  %td= unknown_email.sent_from
  %td= unknown_email.sent_to
  %td= truncate(unknown_email.subject, :length => 150)
  %td= truncate(unknown_email.body, :length => 150)
  %td
    - addresses.each do |address|
      = address
      %p      
        = link_to "Convert to Lead?", convert_unknown_email_path(unknown_email, :email => address), :method => :put
        or
        = link_to "Ignore?", ignore_unknown_email_path(unknown_email, :email => address), :method => :delete

app/views/unknown_emails/index.html.haml
= styles_for :unknown_emails

.title
  %span#unknown_emails_title Unknown Emails

.list
  - if @unknown_emails.any?
    %table.unknown_emails
      %thead
        %tr
          %th Direction
          %th From
          %th To
          %th Subject
          %th Body
          %th Actions
      %tbody#unknown_emails
        = render :partial => 'unknown_email', :collection => @unknown_emails
  - else
    Could not find any emails for unknown leads.

#paginate= render "shared/paginate"